name       : haskell-texmath
version    : 0.9.4
release    : 1
source     :
    - https://hackage.haskell.org/package/texmath-0.9.4/texmath-0.9.4.tar.gz : da665d069708679fb40ee2e981dcdede55e79f3165c0ae09c55621273e682195
license    : GPL-2.0
component  : programming.haskell
summary    : The texmath library provides functions to read and write TeX math, presentation MathML, and OMML (Office Math Markup Language, used in Microsoft Office).
description: |
    The texmath library provides functions to read and write TeX math, presentation MathML, and OMML (Office Math Markup Language, used in Microsoft Office).
builddeps  :
    - haskell-cabal-install
    - haskell-pandoc-types
    - haskell-xml
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
