name       : haskell-texmath
version    : 0.11.0.1
release    : 2
source     :
    - https://hackage.haskell.org/package/texmath-0.11.0.1/texmath-0.11.0.1.tar.gz : 4ec7f6ec41b38d184ca5069440f09ff2b50ff8318809c880f8da79eb6002ac85
license    : GPL-2.0
component  : programming.haskell
summary    : The texmath library provides functions to read and write TeX math, presentation MathML, and OMML (Office Math Markup Language, used in Microsoft Office).
description: |
    The texmath library provides functions to read and write TeX math, presentation MathML, and OMML (Office Math Markup Language, used in Microsoft Office).
builddeps  :
    - haskell-cabal-install
    - haskell-pandoc-types
    - haskell-parsec
    - haskell-xml
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
