name       : haskell-texmath
version    : 0.11.3
release    : 3
source     :
    - https://hackage.haskell.org/package/texmath-0.11.3/texmath-0.11.3.tar.gz : 2e01dd4534f3dba26a4d5ec889dcb2c6195bd0211b125eab305aae41eeea370f
license    : GPL-2.0-only
component  : programming.haskell
summary    : The texmath library provides functions to read and write TeX math, presentation MathML, and OMML (Office Math Markup Language, used in Microsoft Office).
description: |
    The texmath library provides functions to read and write TeX math, presentation MathML, and OMML (Office Math Markup Language, used in Microsoft Office).
builddeps  :
    - haskell-cabal-install
    - haskell-pandoc-types-devel
    - haskell-xml-devel
rundeps    :
    - devel:
        - haskell-pandoc-types-devel
        - haskell-xml-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
